### ISSUE TITLE
Readme: Expected /has/ been proposed: N4109 (N4015).

### ISSUE THREAD

**Issue by martinmoene** [ptal/expected#78]
Heading [Expected](https://github.com/ptal/expected#expected):
.... Expected has been proposed to the C++ standard committee. The current document is [N4109](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4109.pdf). Previous versions are:  [N4015](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4015.pdf).

Heading [Differences from NXXXX](https://github.com/ptal/expected#differences-from-nxxxx): 
- s/NXXXX/N????/

Bring it up to date w.r.t.  N4109/N4015.

**Comment by ptal** [comment]
Thanks.
