### ISSUE TITLE
REQUIRES macro should be in boost namespace

### ISSUE THREAD

**Issue by garyfurnish** [ptal/expected#82]
include/boost/expected/expected.hpp:# define REQUIRES(...) typename std::enable_if<__VA_ARGS__, void*>::type = 0
include/boost/expected/expected.hpp:# define T_REQUIRES(...) typename = typename std::enable_if<(__VA_ARGS__)>::ty

These should be prefixed by BOOST_ to prevent macro namespace contamination (in particular they interfere with the default clang REQUIRES macro for thread safety checking).

**Comment by viboes** [comment]
https://github.com/ptal/expected/commit/234fe47a3776b7c241473a5b9ea1dd9a52783d9a
