### ISSUE TITLE
Warnings in unexpected value

### ISSUE THREAD

**Issue by romikforest** [ptal/expected#83]
Generally we have three sutuation:
- normal: returned expected value
- an error: expected value can't be returned, unexpected value explain the cause.
- warning: returned expected value and some warning unexpected value.

Can class 'expected' help with third situation, return both E and T and be convertable to true?

**Comment by viboes** [comment]
There is another proposal "N4233 - A Class for Status and Optional Value" that goes in this direction.
Each class is used to cover different use cases.

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4233.html
