### ISSUE TITLE
Shouldn't the default `error_traits::make_error` copy in the argument?

### ISSUE THREAD

**Issue by russellmcc** [ptal/expected#92]
Currently, the default `error_traits` class's `make_error` function ignores its argument.  I think this is a mistake, and it should instead pass the argument to the constructor of Error.

**Comment by viboes** [comment]
Maybe you are right. However, currently it doesn't work, because the try-catch in some operations request the constructor of the error from the exception. 

I will see what I can do.

**Comment by viboes** [comment]
https://github.com/ptal/expected/commit/932e6fdf5c8cc908c06a35cbd390ae1efec5d7b8

https://github.com/ptal/expected/commit/fefcc3e8d2a61c4bc96228795c5732ac3ba390f2
